language: node_js

node_js:
  - '15'
  - '10'
  
env:
  - TEST_APP=wf-control
  - TEST_APP=wf-app
  - TEST_APP=wf-admin
  - TEST_APP=e2e
  
os: linux
dist: trusty
sudo: required 


      
before_install:
- chmod +x ./scripts/*.sh

install:
- if [[ $TEST_APP == 'wf-control' ]]; then ./scripts/install-wf-control.sh; fi
- if [[ $TEST_APP == 'wf-app' ]]; then ./scripts/install-wf-app.sh; fi
- if [[ $TEST_APP == 'wf-admin' ]]; then ./scripts/install-wf-admin.sh; fi
- if [[ $TEST_APP == 'e2e' ]]; then ./scripts/install-e2e.sh; fi

script:
- if [[ $TEST_APP == 'wf-control' ]]; then ./scripts/script-wf-control.sh; fi
- if [[ $TEST_APP == 'wf-app' ]]; then ./scripts/script-wf-app.sh; fi
- if [[ $TEST_APP == 'wf-admin' ]]; then ./scripts/script-wf-admin.sh; fi
- if [[ $TEST_APP == 'e2e' ]]; then ./scripts/script-e2e.sh; fi


