# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 15.x]
        TEST_APP: ["wf-control","wf-app","wf-admin","e2e"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: chmod +x ./scripts/*.sh
    - name: Test wf-control
      run: |
        echo $TEST_APP
        cd wf-control
        npm install
        npm test
    - run: if [[ $TEST_APP == 'wf-app' ]]; then ./scripts/install-wf-app.sh; fi
    - run: if [[ $TEST_APP == 'wf-admin' ]]; then ./scripts/install-wf-admin.sh; fi
    - run: if [[ $TEST_APP == 'e2e' ]]; then ./scripts/install-e2e.sh; fi
    - run: if [[ $TEST_APP == 'wf-control' ]]; then ./scripts/script-wf-control.sh; fi
    - run: if [[ $TEST_APP == 'wf-app' ]]; then ./scripts/script-wf-app.sh; fi
    - run: if [[ $TEST_APP == 'wf-admin' ]]; then ./scripts/script-wf-admin.sh; fi
    - run: if [[ $TEST_APP == 'e2e' ]]; then ./scripts/script-e2e.sh; fi
