# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test wf-control
      run: |
        cd wf-control
        npm install
        npm test
    - name: Test wf-app
      run: |
        cd wf-app
        npm install
        npm test
    - name: Test wf-admin
      run: |
        cd wf-admin
        npm install
        npm test
    - name: Test e2e
      run: |
        cd e2e
        npm install
        npm test
